pipeline {
    agent any

    environment {
	GIT_REPO = "https://github.com/juli0806/se_project/"
	MAVEN_HOME = tool name: 'Maven 3', type: 'maven'
    }
	
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                bat 'javac Practice/src/Book.java Practice/src/BookManager.java Practice/src/PerformanceTest.java'
            }
        }
	stage('PerformanceTest') {
	    steps {
	        bat 'java Practice/src/PerformanceTest'
	    }
	}

    }
    
    post {
        always {
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
