pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                bat 'javac -encoding UTF-8 -d classes Practice/src/Book.java Practice/src/BookManager.java Practice/src/PerformanceTest.java'
            }
        }
	stage('PerformanceTest') {
	    steps {
	        bat 'java -cp classes Practice/src/PerformanceTest'
	    }
	}

    }
    
    post {
        always {
            archiveArtifacts 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
